language: python
python:
  - "3.6"

env:
  - CONDA_PYTHON="2.7"
  - CONDA_PYTHON="3.6"

matrix:
  allow_failures:
  - env: CONDA_PYTHON="3.6"

sudo: false

services:
  - postgresql

cache:
  pip: true
  directories:
    - $HOME/miniconda

before_cache:
  - rm -rf $HOME/miniconda/envs/build_env
  - conda clean --yes --quiet --packages

before_install:
  - if [ -f $HOME/miniconda/bin/conda ] ; then
      echo "Using cached miniconda";
    else
      wget --no-verbose https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      rm -rf $HOME/miniconda;
      bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n build_env python=$CONDA_PYTHON
  - source activate build_env
  - make devinstall

script:
  - cp publicdb/settings_develop.py publicdb/settings.py
  - make test

after_success:
  - pip install coveralls codecov
  - coveralls
  - codecov

before_deploy:
  - touch doc/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/_build/html
  email: beheer@hisparc.nl
  name: HiSPARC-Bot
  on:
    branch: master
    python: 2.7
